### ISSUE TITLE
"Header too Large"

### ISSUE THREAD

**Issue by revolvedai** [huchenlei/ComfyUI-IC-Light-Native#32]
Only happens with the bgcombine workflow, for some reason it gives Header Too Large errors. I tried both models, different image sizes, resize settings, checkpoint models, redownloaded the model. Always get this error. The rest of the workflows work fine!

`
Traceback (most recent call last):
  File "/opt/rd/apps/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/opt/rd/apps/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/opt/rd/apps/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/opt/rd/apps/ComfyUI/nodes.py", line 814, in load_unet
    model = comfy.sd.load_unet(unet_path)
  File "/opt/rd/apps/ComfyUI/comfy/sd.py", line 569, in load_unet
    sd = comfy.utils.load_torch_file(unet_path)
  File "/opt/rd/apps/ComfyUI/comfy/utils.py", line 14, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/opt/rd/miniconda3/envs/CMFY/lib/python3.10/site-packages/safetensors/torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
`

**Comment by revolvedai** [comment]
Solved by redownloading model again. :)
