### ISSUE TITLE
Still getting !!! Exception during processing !!! Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 116, 128] to have 4 channels, but got 8 channels instead

### ISSUE THREAD

**Issue by talhadar90** [huchenlei/ComfyUI-IC-Light-Native#46]
I've updated to fix channel padding branch but still getting this error 

WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 12, 3, 3]) != torch.Size([320, 4, 3, 3])
loaded completely 0.0 1639.406135559082 True
  0%|          | 0/25 [00:00<?, ?it/s]
!!! Exception during processing !!! Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 116, 128] to have 4 channels, but got 8 channels instead
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ubuntu/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/ubuntu/ComfyUI/nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/ubuntu/ComfyUI/nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/sampling.py", line 116, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 116, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 420, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/k_diffusion/sampling.py", line 688, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/home/ubuntu/ComfyUI/comfy/samplers.py", line 226, in calc_cond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-IC-Light-Native/ic_light_nodes.py", line 116, in wrapper_func
    return existing_wrapper(unet_apply, params=apply_c_concat(params))
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-IC-Light-Native/ic_light_nodes.py", line 108, in unet_dummy_apply
    return unet_apply(x=params["input"], t=params["timestep"], **params["c"])
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 68, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 852, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "/home/ubuntu/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 50, in forward_timestep_embed
    x = layer(x)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/comfy/ops.py", line 106, in forward
    return super().forward(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 116, 128] to have 4 channels, but got 8 channels instead

**Comment by ezekiel23533** [comment]
same

**Comment by billerss11** [comment]
Had the same problem. First you need to make sure you installed [layerdiffuse]. What works for me is to upgrade this custom node via comfyUI manager. Click "try update" button.

**Comment by aiartxx02** [comment]
same

**Comment by migo516** [comment]
same

**Comment by talhadar90** [comment]
> Had the same problem. First you need to make sure you installed [layerdiffuse]. What works for me is to upgrade this custom node via comfyUI manager. Click "try update" button.

Have you updated your comfyUI?

**Comment by migo516** [comment]
> > Had the same problem. First you need to make sure you installed [layerdiffuse]. What works for me is to upgrade this custom node via comfyUI manager. Click "try update" button.
> 
> Have you updated your comfyUI?

LayerDiffuse encounters the same error even when properly installed and loaded. The same workflow functions correctly in ComfyUI 0.10. However, in upgraded versions of ComfyUI, the aforementioned error occurs.
Version 0.10 operates on 2.3.1+cu121, while the upgraded versions run on 2.4.0+cu121. For testing purposes, I recently installed version v0.1.3 separately and tested the same workflow, resulting in the same error.
In the current situation, temporary solutions to test include:

Using ComfyUI v0.1.0
Installing the latest version of ComfyUI and then downgrading to 2.3.1+cu121
Using ComfyUI-IC-Light instead of ComfyUI-IC-Light-Native

**Comment by huchenlei** [comment]
Update your ComfyUI and this extension to latest veresion. https://github.com/huchenlei/ComfyUI-IC-Light-Native/pull/43 should fix this issue.

**Comment by GuardSkill** [comment]
> I found a solution. Delete ComfyUI-IC-Light-Native and use ComfyUI-IC-Light. Go to ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light where IC-Light is installed, open CMD, and type git pull to run it. The update will proceed and no errors will occur afterward. There are many cases where the update does not proceed properly even when ComfyUI-Manager is updated, so proceed with the update as above.
Thanks for your hint. I solved it.      by git pull native

**Comment by JimWang151** [comment]
> > I found a solution. Delete ComfyUI-IC-Light-Native and use ComfyUI-IC-Light. Go to ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light where IC-Light is installed, open CMD, and type git pull to run it. The update will proceed and no errors will occur afterward. There are many cases where the update does not proceed properly even when ComfyUI-Manager is updated, so proceed with the update as above.
> > Thanks for your hint. I solved it.      by git pull native

Are u kidding ?Delele ComfyUI-IC-Light-Native？

 ComfyUI-IC-Light-Native and use ComfyUI-IC-Light are different node and use different UNET,i found that the way of lighting solution been reached is more better than ComfyUI-IC-Light, now i want to use ComfyUI-IC-Light-Native but you tell use delele it ?

**Comment by GuardSkill** [comment]
https://github.com/huchenlei/ComfyUI-IC-Light-Native/issues/47#issuecomment-2315243914  @JimWang151

**Comment by JimWang151** [comment]
> [#47 (comment)](https://github.com/huchenlei/ComfyUI-IC-Light-Native/issues/47#issuecomment-2315243914) @JimWang151

I think IC-Light and Ic-light native no relationship.
